
version: "3.9"
services:
  backend:
    build: .
    container_name: signlang_backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=dev_secret
      - REFRESH_SECRET_KEY=dev_refresh
